steps:
  - name: 'node:20.13.1-alpine'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        npm install
        npm run build

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/marcelocarveche:$COMMIT_SHA', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/marcelocarveche:$COMMIT_SHA']

images:
  - 'gcr.io/$PROJECT_ID/marcelocarveche:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
